### ISSUE TITLE
Issues with Nvme Direct2

### ISSUE THREAD

**Issue by balamsg** [nvmedirect/nvmedirect_v2#1]
Hi,
   I have downloaded the nvmedirect_v2 and faced the following issues.
1) Tried to compile the NVMe direct code in Ubuntu 17 with kernel version 4.14 but there were lot of compilation issues but the same code was compiling properly in 4.10.0 version of kernel. Is the NVMe direct not compatible for newer versions of kernel?

2) In mkfs.c, the ffs_format() & ffs_init(), function definition arguments are different compared to actual function arguments. 

3) When i try to do a modprobe nvmed , i am getting a kernel oops in "disk_part_iter_init()" where the ns->disk variable is NULL. (PS: i have inserted the nvme driver earlier)

4. Please provide a readme of how to use & test the forestfs.

**Comment by hyeongjunkim** [comment]
Dear @balamsg,

Thanks for your interests on NVMeDirect framework.

The uploaded code is very prototypical and we will upload a new framework in a few days.
Perhaps it is NVMeDirect_v3??.
Instead of this code, please wait and wait for a new framework to be uploaded within a few days.
I will post it with the manual for operation.

Thanks.
